try :               #exception use korle code a vul thakleo sesh porjonto code run hobe
    result = 45/0
except:
    print("error happened")
finally:
    print('finally here')

print('done')